### ISSUE TITLE
Error building the "simple version"

### ISSUE THREAD

**Issue by akatechis** [dflemstr/rust-native-wasm-loader#13]
I'm trying to build the simple version from the README, and getting the following error. I get a similar error when I try running building the project in "watch" mode using `webpack-serve`.

Stack:
```
ERROR in ./src/lib.rs
Module build failed: TypeError: (0 , _util.promisify) is not a function
    at Object.<anonymous> (F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:32:39)
    at Module._compile (F:\workspace\project\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (F:\workspace\project\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (F:\workspace\project\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\workspace\project\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\workspace\project\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\workspace\project\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\workspace\project\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\workspace\project\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (F:\workspace\project\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (F:\workspace\project\node_modules\webpack\lib\NormalModule.js:219:3)
    at NormalModule.build (F:\workspace\project\node_modules\webpack\lib\NormalModule.js:337:15)
    at Compilation.buildModule (F:\workspace\project\node_modules\webpack\lib\Compilation.js:346:10)
    at factory.create (F:\workspace\project\node_modules\webpack\lib\Compilation.js:572:15)
    at factory (F:\workspace\project\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (F:\workspace\project\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (F:\workspace\project\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at resolver (F:\workspace\project\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (F:\workspace\project\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./src/index.js 1:0-31 3:0-7
```

I'm on Windows 10, using the following:

`rustc 1.24.0 (4d90ac38c 2018-02-12)`
`cargo 0.25.0 (8c93e0895 2018-02-01)`
`node v7.9.0`
`npm v5.6.0`

And the following dependencies in `package.json`:

```
    "rust-native-wasm-loader": "^0.6.5",
    "wasm-loader": "^1.3.0",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.10",
    "webpack-serve": "^0.1.4"
```

**Comment by akatechis** [comment]
Somehow, removing all my `node_modules` and reinstalling seems to have cleared the issue, but I'm getting a different error. Will open a different issue for that.

**Comment by akatechis** [comment]
Actually, I think it might have been fixed by upgrading to the latest version of NodeJS.
