### ISSUE TITLE
Invalid Version with default config from README and wasm-bindgen

### ISSUE THREAD

**Issue by jaywunder** [dflemstr/rust-native-wasm-loader#26]
I'm using wasm-bindgen to load a rust file into my react project.  My webpack config for .rs files looks like this:
```
{
        test: /\.rs$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              compact: true,
            }
          },
          {
            loader: 'rust-native-wasm-loader',
            options: {
              release: true,
              wasmBindgen: {
                wasm2es6js: true,
              },
            }
          }
        ]
      }
```
which is the default config from the README.  But I'm getting this error.  Any advice on how to fix this?

```
ERROR in ./stutter/src/lib.rs
Module build failed: TypeError: Invalid Version: (5f799e543)
    at new SemVer (/Users/jacob/Documents/stutter-ide/node_modules/semver/semver.js:305:11)
    at Range.test (/Users/jacob/Documents/stutter-ide/node_modules/semver/semver.js:1112:15)
    at Object.satisfies (/Users/jacob/Documents/stutter-ide/node_modules/semver/semver.js:1161:16)
    at /Users/jacob/Documents/stutter-ide/node_modules/rust-native-wasm-loader/dist/index.js:59:17
    at Generator.next (<anonymous>)
    at step (/Users/jacob/Documents/stutter-ide/node_modules/rust-native-wasm-loader/dist/index.js:38:191)
    at /Users/jacob/Documents/stutter-ide/node_modules/rust-native-wasm-loader/dist/index.js:38:361
 @ ./src/App.js 15:11-43
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js
```

**Comment by dflemstr** [comment]
Aha, are you running a version of `wasm-bindgen` that you compiled yourself? That error means that it couldn't parse the `wasm-bindgen` version number correctly.

**Comment by jaywunder** [comment]
Thanks for the answer, I don't believe I did compile it myself, I just did `cargo install wasm-bindgen-cli`.  Weird... I just ran that command again and now it works! Well thanks for your time haha.  Hopefully this helps someone else too.
